### PR TITLE
Fixes on web-control module

### PR DESCRIPTION
**Pull request by cmiguelcabral**
- corrected gpio for 05CM
- some improvements on the web interface

sorry for the whitespaces, auto-ident is on...

### CODE REVIEW

**Comment by thewh1teagle** [comment]
@cmiguelcabral 
Thank you very much for your contribute!
Did you tested it?

**Comment by cmiguelcabral** [comment]
> @cmiguelcabral
> Thank you very much for your contribute!
> Did you tested it?

Hi, 

That's my pleasure!

Yes, I tested it and the leds are working.
I just cannot make the motor to work, motord does not start. And also onvif is not working.

**Comment by thewh1teagle** [comment]
@cmiguelcabral 
What's the error you got when you tried to run motord on your camera?
I can't try myself because I don't have that camera, mine is 02cm.

**Comment by cmiguelcabral** [comment]
That's what I get:

`
 ./motord
-sh: ./motord: not found
`
The same happens on onvif_srvd

**Comment by cmiguelcabral** [comment]
I also tried to copy from telmomarques hacks and I get this:
```
: symbol '__pthread_cleanup_upto': can't resolve symbol
: symbol 'stdout': can't resolve symbol
: symbol 'daylight': can't resolve symbol
: symbol '__libc_stack_end': can't resolve symbol
: symbol '__stack_chk_guard': can't resolve symbol
: symbol 're_syntax_options': can't resolve symbol
: symbol '_dl_secure': can't resolve symbol
Segmentation fault
```

**Pull request merged**
